## Global Variabel
@BaseUrl = https://pam-2026-p4-ifs18005-be.delcom.org:8080
#@BaseUrl = http://127.0.0.1:8000


## Profile
## ===========================================

### Mengambil data profil
# @name GetProfile
GET {{BaseUrl}}/profile
Content-Type: application/json

### Mengambil photo profil
# @name GetProfilePhoto
GET {{BaseUrl}}/profile/photo
Content-Type: application/json



## Plants
## ===========================================

### Mengambil semua data tumbuhan
# @name GetAllPlants
GET {{BaseUrl}}/plants?search=
Content-Type: application/json

#> {%
#    client.global.set("plantId", response.body.data.plants[0].id);
#    console.log(client.global.get("plantId"))
#%}

### Menambahkan data tumbuhan baru
# @name PostPlants
POST {{BaseUrl}}/plants
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Kangkung
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Kangkung adalah sayuran hijau yang kaya vitamin dan serat
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Membantu pencernaan dan menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Dapat menyebabkan kembung jika berlebihan
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

> {%
    client.global.set("plantId", response.body.data.plantId);
    console.log(client.global.get("plantId"))
%}

### Mengambil data tumbuhan berdasarkan id
# @name GetPlantById
GET {{BaseUrl}}/plants/{{plantId}}
Content-Type: application/json

### Mengambil gambar tumbuhan
# @name GetPlantImageById
GET {{BaseUrl}}/plants/{{plantId}}/image
Content-Type: application/json

### Mengubah data tumbuhan (tanpa ganti gambar)
# @name PutPlantOnlyData
PUT {{BaseUrl}}/plants/{{plantId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Kangkung Update
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Kangkung segar hasil update
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Menambah energi dan menjaga pencernaan
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Tidak dianjurkan untuk penderita asam lambung
--WebAppBoundary--

### Mengubah data tumbuhan + gambar
# @name PutPlant
PUT {{BaseUrl}}/plants/{{plantId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Kangkung
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Kangkung hijau segar
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Tidak dianjurkan dikonsumsi berlebihan
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

### Menghapus data tumbuhan
# @name DeletePlant
DELETE {{BaseUrl}}/plants/{{plantId}}
Content-Type: application/json



## Drinks
## ===========================================

### Mengambil semua data minuman
# @name GetAllDrinks
GET {{BaseUrl}}/drinks?search=
Content-Type: application/json

#> {%
#    client.global.set("drinkId", response.body.data.drinks[0].id);
#    console.log(client.global.get("drinkId"))
#%}

### Menambahkan data minuman (contoh: Bajigur)
# @name PostDrinkBajigur
POST {{BaseUrl}}/drinks
Content-Type: application/json

{
  "nama": "Bajigur",
  "deskripsi": "Minuman tradisional khas Sunda berbahan santan dan gula aren",
  "bahanUtama": "Santan, gula aren, jahe",
  "caraPenyajian": "Disajikan hangat dalam gelas",
  "manfaat": "Menghangatkan tubuh dan meredakan masuk angin"
}

> {%
    client.global.set("drinkId", response.body.data.drinkId);
    console.log(client.global.get("drinkId"))
%}

### Mengambil data minuman berdasarkan id
# @name GetDrinkById
GET {{BaseUrl}}/drinks/{{drinkId}}
Content-Type: application/json

### Mengubah data minuman (contoh: Bandrek)
# @name PutDrink
PUT {{BaseUrl}}/drinks/{{drinkId}}
Content-Type: application/json

{
  "nama": "Bandrek",
  "deskripsi": "Minuman tradisional berbahan jahe dan rempah-rempah",
  "bahanUtama": "Jahe, gula merah, rempah-rempah",
  "caraPenyajian": "Disajikan hangat dan diminum perlahan",
  "manfaat": "Membantu meredakan flu dan menghangatkan badan"
}

### Menghapus data minuman
# @name DeleteDrink
DELETE {{BaseUrl}}/drinks/{{drinkId}}
Content-Type: application/json